project_id = "ljygreayxxpsdmncwzia"

[functions.generate-sitemap]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.auto-translate]
verify_jwt = true